version: "3.9"

services:
  db:
    image: postgres:14
    container_name: ford_postgres
    restart: always
    environment:
      POSTGRES_USER: dev_ford
      POSTGRES_PASSWORD: 34852
      POSTGRES_DB: FORD_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ford_net

  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ford_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - ford_net

volumes:
  postgres_data:

networks:
  ford_net:
